version: '3.4'

services:
  api:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - db
      - redis
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: 
      DB_NAME: rrhh
      REDIS_HOST: redis  # Agrega la variable de entorno para Redis
      REDIS_PORT: 6379
    volumes:
      - .:/app  # Asegúrate de que esta ruta sea correcta
    networks:
      - app-network

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: rrhh
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_HOST: '%'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d  

    ports:
      - "3307:3306"
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
